# Generated by Django 4.2.4 on 2023-09-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('enabled', models.BooleanField()),
                ('current_count', models.IntegerField()),
                ('max_count', models.IntegerField()),
                ('flagship_event', models.BooleanField()),
                ('only_males', models.BooleanField()),
                ('only_females', models.BooleanField()),
                ('path', models.CharField(max_length=100)),
                ('t_and_c', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-flagship_event', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=40)),
                ('academic_year', models.CharField(max_length=10)),
                ('registered_academic_year', models.CharField(max_length=30)),
                ('registered_semester', models.IntegerField()),
                ('module', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=10)),
                ('current_add', models.CharField(max_length=100)),
                ('prn', models.BigIntegerField()),
                ('roll', models.BigIntegerField()),
                ('contact_num', models.FloatField()),
                ('verified', models.IntegerField()),
                ('submitted', models.IntegerField()),
                ('Objective_of_the_Activity', models.CharField(max_length=1000, null=True)),
                ('Description_of_the_Activity', models.CharField(max_length=1000, null=True)),
                ('Benefits_to_Society', models.CharField(max_length=1000, null=True)),
                ('Benefits_to_Self', models.CharField(max_length=1000, null=True)),
                ('Learning_Experiences_challenges', models.CharField(max_length=1000, null=True)),
                ('How_did_it_help_you_to_shape_your_Empathy', models.CharField(max_length=1000, null=True)),
                ('url', models.URLField(max_length=1000, null=True)),
                ('Secretary', models.CharField(max_length=40, null=True)),
                ('activity', models.CharField(max_length=20, null=True)),
                ('flagshipEvent', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=20, null=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('sent_certificate', models.BooleanField(default=False)),
                ('marked_attendance_GP2', models.BooleanField(default=False)),
                ('marked_attendance_FE', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Coordinators',
                'ordering': ['cname'],
            },
        ),
        migrations.CreateModel(
            name='currentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=15)),
                ('AcademicYear', models.CharField(max_length=30)),
                ('Semester', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Current-Data',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('enabled', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('enabled', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Domains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=40)),
                ('academic_year', models.CharField(max_length=10)),
                ('registered_academic_year', models.CharField(max_length=30)),
                ('registered_semester', models.IntegerField(default=2)),
                ('domain', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=10)),
                ('current_add', models.CharField(max_length=100)),
                ('prn', models.BigIntegerField()),
                ('roll', models.BigIntegerField()),
                ('contact_num', models.FloatField()),
                ('password_changed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Secretaries',
                'ordering': ['sname'],
            },
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('uCount', models.IntegerField()),
                ('vCount', models.IntegerField()),
                ('cCount', models.IntegerField()),
                ('sCount', models.IntegerField()),
                ('totalLogins', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('falied_registration', models.IntegerField()),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('activity', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=40)),
                ('academic_year', models.CharField(max_length=10)),
                ('registered_academic_year', models.CharField(max_length=30)),
                ('registered_semester', models.IntegerField()),
                ('module', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=10)),
                ('current_add', models.CharField(max_length=200)),
                ('prn', models.BigIntegerField()),
                ('roll', models.BigIntegerField()),
                ('contact_num', models.FloatField()),
                ('verified', models.IntegerField(default=0)),
                ('submitted', models.IntegerField(default=0)),
                ('Objective_of_the_Activity', models.CharField(max_length=1000, null=True)),
                ('Description_of_the_Activity', models.CharField(max_length=1000, null=True)),
                ('Benefits_to_Society', models.CharField(max_length=1000, null=True)),
                ('Benefits_to_Self', models.CharField(max_length=1000, null=True)),
                ('Learning_Experiences_challenges', models.CharField(max_length=1000, null=True)),
                ('How_did_it_help_you_to_shape_your_Empathy', models.CharField(max_length=1000, null=True)),
                ('url', models.URLField(max_length=1000, null=True)),
                ('Cordinator', models.CharField(max_length=40, null=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('sent_certificate', models.BooleanField(default=False)),
                ('attendance', models.CharField(max_length=350, null=True)),
            ],
            options={
                'ordering': ['vname'],
            },
        ),
    ]
