# Generated by Django 5.1.4 on 2025-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('divisions', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('activities', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='divisions',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='roll_nos',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
