# Generated by Django 4.2.4 on 2023-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='t_and_c',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
