# Generated by Django 5.1.4 on 2025-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_domainallotment_activity_divisions_event_roll_nos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainallotment',
            name='divisions',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
