# Generated by Django 4.2.4 on 2023-09-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_activity_path_alter_activity_t_and_c"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="attendance",
            field=models.CharField(default="", max_length=350),
        ),
    ]
