# Generated by Django 4.2.4 on 2023-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_volunteer_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinator",
            name="blood_group",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="coordinator",
            name="parent_num",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="blood_group",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="parent_num",
            field=models.FloatField(default=0.0),
        ),
    ]
