# Generated by Django 5.1.4 on 2025-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_domainallotment_divisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainallotment',
            name='activities',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='domainallotment',
            name='divisions',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='domainallotment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
