# Generated by Django 3.2.25 on 2025-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_domainallotment_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='marked_IN_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
