# Generated by Django 4.2.4 on 2023-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_coordinator_blood_group_coordinator_parent_num_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="dept",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="dept",
            field=models.CharField(max_length=60),
        ),
    ]
