# Generated by Django 5.1.4 on 2025-01-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_volunteer_marked_in_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='activity',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='cname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='domain',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='activity',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='sname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='vname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
