# Generated by Django 4.2.4 on 2023-09-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_coordinator_dept_alter_volunteer_dept"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="report_filling",
            field=models.BooleanField(default=False),
        ),
    ]
