# Generated by Django 4.2.4 on 2023-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_activity_report_filling"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("user_type", models.CharField(default="", max_length=30)),
                ("activity", models.CharField(default="", max_length=20)),
                ("reason", models.CharField(default="", max_length=300)),
                ("Time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Failed Registrations",
            },
        ),
    ]
