# Generated by Django 5.1.4 on 2025-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_coordinator_activity_alter_coordinator_cname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretary',
            name='domain',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
