# Generated by Django 4.2.4 on 2023-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_failedregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinator",
            name="marked_IN_FE",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coordinator",
            name="marked_IN_GP2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="marked_IN_attendance",
            field=models.BooleanField(default=False),
        ),
    ]
