# Generated by Django 5.1.4 on 2025-01-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_attendance_marked_in_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_IN_attendance',
        ),
    ]
