# Generated by Django 4.0.6 on 2025-02-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_attendance_attendance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-time'], 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', 'start_time'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dataCollectionMarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='reportFillingMarks',
            field=models.IntegerField(default=0),
        ),
    ]
