# Generated by Django 4.2.4 on 2023-09-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_activity_allotment_count_activity_allotment_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="code",
            field=models.CharField(default="", max_length=10),
        ),
    ]
