# Generated by Django 4.2.4 on 2023-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_activity_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="allotment_count",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="falied_registration",
        ),
    ]
