# Generated by Django 4.2.4 on 2023-09-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_remove_activity_allotment_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinator",
            name="flagship_event_head",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="coordinator",
            name="social_services_head",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
