# Generated by Django 4.2.4 on 2023-09-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_coordinator_flagship_event_head_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretary",
            name="activity",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
