# Generated by Django 4.2.4 on 2023-10-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_coordinator_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinator",
            name="flagship_event_head",
        ),
        migrations.RemoveField(
            model_name="coordinator",
            name="social_services_head",
        ),
    ]
