# Generated by Django 4.2.4 on 2023-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_alter_secretary_dept"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="message",
            field=models.CharField(default="", max_length=600),
        ),
    ]
