# Generated by Django 4.2.4 on 2023-10-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_falcultyadvisor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FalcultyAdvisor",
            new_name="GuardianFaculty",
        ),
    ]
