# Generated by Django 4.2.4 on 2023-10-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0020_rename_falcultyadvisor_guardianfaculty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guardianfaculty",
            options={"ordering": ["name"], "verbose_name_plural": "Guardian Faculties"},
        ),
        migrations.AddField(
            model_name="volunteer",
            name="guardian_faculty",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
