# Generated by Django 4.2.4 on 2023-10-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0021_alter_guardianfaculty_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="guardian_faculty",
        ),
    ]
