# Generated by Django 4.2.4 on 2023-10-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_volunteer_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="rejection_reason",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
