# Generated by Django 4.2.4 on 2023-10-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_volunteer_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="report_verification",
            field=models.BooleanField(default=False),
        ),
    ]
