# Generated by Django 4.2.4 on 2023-10-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_activity_report_verification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinator",
            name="module",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="module",
        ),
    ]
