# Generated by Django 4.2.4 on 2023-11-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_remove_activity_code_remove_activity_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pasted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("activity", models.CharField(default="", max_length=10)),
            ],
            options={
                "verbose_name_plural": "Pasted",
            },
        ),
    ]
