# Generated by Django 4.2.4 on 2023-11-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_pasted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="message",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
