# Generated by Django 4.2.4 on 2023-11-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_alter_activity_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pasted",
        ),
    ]
