# Generated by Django 4.2.4 on 2023-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0031_delete_pasted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinator",
            name="sent_certificate",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="character",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="sent_certificate",
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="rejection_reason",
            field=models.CharField(default="none", max_length=200),
        ),
    ]
