# Generated by Django 4.2.4 on 2023-12-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0032_remove_coordinator_sent_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="profile_edited",
            field=models.CharField(default="", max_length=10),
        ),
    ]
