# Generated by Django 4.2.8 on 2023-12-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0034_alter_volunteer_contact_num_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="allotment_done",
        ),
    ]
