# Generated by Django 4.2.8 on 2023-12-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0035_remove_activity_allotment_done"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FailedRegistration",
        ),
    ]
