# Generated by Django 5.0 on 2024-01-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0038_alter_coordinator_contact_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="allow_failed_volunteers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="allow_passed_volunteers",
            field=models.BooleanField(default=False),
        ),
    ]
