# Generated by Django 5.0 on 2024-02-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0039_activity_allow_failed_volunteers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["name"], "verbose_name_plural": "Activities"},
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="marked_IN_attendance",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
