# Generated by Django 5.0 on 2024-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0040_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="attendance",
            field=models.BooleanField(default=False),
        ),
    ]
