# Generated by Django 5.0 on 2024-07-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0041_activity_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="allow_passed_volunteers",
        ),
    ]
